<?php

/**
 * @file
 * Installation file for the OAuth2 Authentication module.
 */

/**
 * Implements hook_uninstall().
 */
function oauth2_leagueauthentication_uninstall() {

  // Delete the configuration.
  variable_del('oauth2_leagueauthentication_token_endpoint');
  variable_del('oauth2_leagueauthentication_client_id');
  variable_del('oauth2_leagueauthentication_client_secret');
  variable_del('oauth2_leagueauthentication_scope');
  variable_del('oauth2_leagueauthentication_class');
  variable_del('oauth2_leagueauthentication_user_edit_email');
  variable_del('oauth2_leagueauthentication_user_edit_password');
}
